src/Ps_FacetedsearchRangeAggregator.php
| Branch?       | dev
| Description?  | The number of products in the ranges should include the products from the lower bounds
| Category?     | MO
| Fixed ticket? | http://forge.prestashop.com/browse/BOOM-338
| How to test?  | <ul><li>BO: Create some products</li><li>BO: Activate the price filter in the facetted search module configuration</li><li>FO: The totals of the ranges should match the products you created</li></ul>
=> Fix the price ranges

src/Ps_FacetedsearchFiltersConverter.php
| Branch?       | develop
| Description?  | allow to setProperty('color') only for color or textures factets
| Category?     | FO
| BC breaks?    | yes or no ?
| Deprecations? | yes or no ?
| Fixed ticket? | [BOOM-3454](http://forge.prestashop.com/browse/BOOM-3454)
| How to test?  | before fix attributes in facated search are treated as color options so they design is bad
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/prestashop/ps_facetedsearch/26)
=> Fix for texture added to not color groups

ps_facetedsearch.php
Fixes notices about `count()` must be used on a value which implements Countable.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/prestashop/ps_facetedsearch/30)
=> Fix notices of PHP 7.2

.travis.yml, composer.json, composer.lock, src/Adapter/AbstractAdapter.php, src/Filters/Block.php, src/Product/Search.php, tests/php/phpstan/bootstrap.php, tests/php/phpstan/phpstan.neon
This PR adds several checks to Travis:
* PHP syntax lint
* PHP Unit (When tests will be added)
* CS Fixer
* PHP Stan
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/prestashop/ps_facetedsearch/55)
=> Add PHP checks on Travis

ps_facetedsearch-attribute-indexer.php, ps_facetedsearch-price-indexer.php, ps_facetedsearch.php, src/Filters/Block.php
Tests:
- Enable multistore context
- Create a new shop
- Create templates for each store
- Reindex and clear caches.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/prestashop/ps_facetedsearch/70)
=> Reindex multistore correctly

ps_facetedsearch.php
Failure to index prices in case of tax inactivity
If the "Use tax to filter price" setting is disabled, the price index will not be executed correctly and the price slider will not be displayed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/prestashop/ps_facetedsearch/89)
=> fix bug indexed prices

src/Filters/Block.php
Fixes https://github.com/PrestaShop/PrestaShop/issues/14394
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/prestashop/ps_facetedsearch/104)
=> Split currency if a ; is present in the format string

ps_facetedsearch.php
Fix for issue report https://github.com/PrestaShop/PrestaShop/issues/14423
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/prestashop/ps_facetedsearch/105)
=> Fix for cache problem when used as widget

src/Filters/Converter.php, src/Product/SearchProvider.php
You should be able to see a facet even if you have only one filter.
See https://github.com/PrestaShop/PrestaShop/issues/9647 for more explanation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/prestashop/ps_facetedsearch/103)
=> Fix facet display when there is only one filter

ps_facetedsearch.php, src/Filters/Converter.php, src/Product/SearchProvider.php, views/templates/admin/_functions/show_limit.tpl, views/templates/admin/add.tpl, views/templates/admin/view.tpl
Fixes: https://github.com/PrestaShop/PrestaShop/issues/9813
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/prestashop/ps_facetedsearch/102)
=> Make filter show limit working again

ps_facetedsearch.php
Remove unwanted curl which is sometimes failing
Tests:
Make sure you can install / upgrade the module :)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/prestashop/ps_facetedsearch/117)
=> Remove unwanted curl

src/Filters/Converter.php, tests/php/FacetedSearch/Filters/ConverterTest.php
- Only sort by magnitude if there is a filters show limitations
- Do not sort attributes by label
Fixes: https://github.com/PrestaShop/PrestaShop/issues/15065
https://github.com/PrestaShop/PrestaShop/issues/14989
Specs: 
[https://github.com/PrestaShop/prestashop-specs/blob/master/ps_facetedsearch.md#sorting](https://github.com/PrestaShop/prestashop-specs/blob/master/ps_facetedsearch.md#sorting) 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/prestashop/ps_facetedsearch/124)
=> Refactoring values sorting

src/Product/Search.php, tests/php/FacetedSearch/Product/SearchTest.php
Fixes https://github.com/PrestaShop/PrestaShop/issues/15062
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/prestashop/ps_facetedsearch/125)
=> Products are displayed in wrong order when sorted by "position" and "Show products from subcategories" is disabled 

src/Product/SearchProvider.php, tests/php/FacetedSearch/Product/SearchProviderTest.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/prestashop/ps_facetedsearch/135)
=> Use fetch method instead of render to allow override

src/Filters/Block.php, src/Filters/Converter.php, tests/php/FacetedSearch/Filters/BlockTest.php
Fixes https://github.com/PrestaShop/PrestaShop/issues/15688
It should use the Public name instead of Name property for attributes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/prestashop/ps_facetedsearch/144)
=> Use public_name instead of name for attribute group

.travis.yml, tests/php/phpstan/phpstan-1.7.1.2.neon, tests/php/phpstan/phpstan-1.7.2.5.neon, tests/php/phpstan/phpstan-1.7.3.4.neon, tests/php/phpstan/phpstan-1.7.4.4.neon, tests/php/phpstan/phpstan-1.7.5.1.neon
Just split phpstan configuration.
No need QA.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/prestashop/ps_facetedsearch/146)
=> Use specific prestashop version for phpstan

config/index.php, config/services.yml, src/Constraint/UrlSegment.php, src/Constraint/UrlSegmentValidator.php, src/Form/Feature/FormModifier.php, tests/php/phpstan/phpstan-1.7.1.2.neon, tests/php/phpstan/phpstan-1.7.2.5.neon
This module adds 2 new fields in PrestaShop's feature edit form. The validation of the URL field was incorrectly implemented in this PR: https://github.com/PrestaShop/ps_facetedsearch/pull/133
With this PR it should validate URL value the same way as it was validating prior to https://github.com/PrestaShop/ps_facetedsearch/pull/133 PR
https://prnt.sc/pebc50
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/prestashop/ps_facetedsearch/145)
=> Fix url validation

ps_facetedsearch.php
Something has changed on develop branch, this clear cache button displays an error message even if the cache is cleared
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/prestashop/ps_facetedsearch/149)
=> Clear cache button displays an error even on success

ps_facetedsearch.php
If you have several shop with different default country, indexation of price are base only on the default country of the default shop.
For instance, you can create a shop in France and a shop in USA with only one currency.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/prestashop/ps_facetedsearch/157)
=> Fix order by price indexation without tax rate

ps_facetedsearch.php
Hi, I think the condition to skip default prices is too wide here.
I have a shop where I define base prices in default currency.
Prices for other currencies are defined using specific prices, in order to avoid rounding issues due to exchange rates.
The price calculation for such a product then is:
default currency: default price
other currencies: specific price.
The logic for indexing a products price in this file looks for ANY specific price rule, regardless of id_currency/id_country for the product, and if it finds one, the default price is never used.
As a result in my price index, for default currency (no specific rule) all products are indexed with zero price.
--- …
=> Fix price indexing for products with specific prices only for some currencies

src/Adapter/MySQL.php, src/Product/Search.php, src/Product/SearchFactory.php, src/Product/SearchProvider.php
| Description?  | A module can easily provide a custom search provider but often what the ps_faceted_search module does is 90% what is needed.  At the moment, this module is difficult to reuse and customizing the search requires a completely new implementation.  This PR would allow a module to reuse ps_faceted_search implementation while allowing for some customization, in the building of the query in particular.
| Fixed ticket? | Fixes PrestaShop/Prestashop#20865
| How to test?  | `composer run test`
--- …
=> Allow customization of parts of the search without total rewrite

src/Hook/Feature.php
| Description?  | The version condition is not enough, we should display the hook only if the migrated page is loaded.
| Fixed ticket? | Fixes PrestaShop/Prestashop#21546
| How to test?  | Load feature form in 1.7.7.x and on develop branch.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/prestashop/ps_facetedsearch/239)
=> Add flag to change the page is migrated

src/Filters/Converter.php
| Description?  | Don't care about the parent category id.
| Fixed ticket? | Fixes PrestaShop/Prestashop#16067
| How to test?  | Follow ticket instruction.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/prestashop/ps_facetedsearch/272)
=> Only check the category name, ignore parent id

ps_facetedsearch.php
| Description?  | When you configure default sort by for category page with value `sort by price` and products in category don't have a tax configured (without tax) or an option `use taxes` is disabled in the module and you have more than one country configured for current shop, so in this case you will not see products in category. It happens only when you access FO using customer that country is different from the default country. The module tries to make joins by current country id, but price index use only default country for each shop/product (the line is not present in DB, because we made indexes only for default country). To fix this problem i propose to fetch activated countries for …
=> Fix order by price indexation without tax rate (default country fix)

ps_facetedsearch.php
| Description?  | The third parameter is about attribute_id as you can see on this image![image](https://user-images.githubusercontent.com/1462701/102127637-0ad3f900-3e4d-11eb-9ce9-20e0b206c160.png) <br>Thanks @zuk3975 :wink: 
| How to test?  | No need QA.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/prestashop/ps_facetedsearch/289)
=> The third parameter is about attribute and not country id

ps_facetedsearch.php
| Description?  | Do not use Tools method, it's useless here.
| Fixed ticket? | Fixes PrestaShop/Prestashop#15475
| How to test?  | Try to save a feature value with a wrong URL. See error message.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/prestashop/ps_facetedsearch/297)
=> Fix error message

src/Product/Search.php, tests/php/FacetedSearch/Product/SearchTest.php
| Description?  | Make sure the minPrice is lower than the price_max, and maxPrice higher than price_min in layered_price_index table
| Fixed ticket? | Fixes PrestaShop/Prestashop#16822
| How to test?  | See ticket.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/prestashop/ps_facetedsearch/300)
=> Optimize price search

ps_facetedsearch.php
| Description?  | Because of wrong SQL queries, installing this module over the old blocklayered one in the BO fails. Also, when deleting it, the table `ps_layered_friendly_url` is still in the DB.
| Fixed ticket? | Partially PrestaShop/Prestashop#22668
| How to test?  | 1. On PS 1.7.x.x, uninstall any existing ps_facetedsearch or blocklayered module.<br>2. Check that your DB doesn't have any table starting with `ps_layered_*`.<br>3. Install [this **modified** version of blocklayered](https://github.com/PrestaShop/ps_facetedsearch/files/5787806/blocklayered.zip) (only the compatibility range has been changed so we can …
=> Fix migration from blocklayered

src/Adapter/MySQL.php, tests/php/FacetedSearch/Adapter/MySQLTest.php
| Description?  | When sorting products and they have the same price or the same ORDER BY in the database and this one has cache disable, the sort is random as it's explained in the issue. To be sure it never occurred, always add a second sort by id_product DESC
| Fixed ticket? | Fixes PrestaShop/Prestashop#18674
| How to test?  | Turn off the `query_cache_type` in your MySQL session (show cache values with `SHOW VARIABLES LIKE '%query_cache%'`)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/prestashop/ps_facetedsearch/295 …
=> Always sort by id_product when there is similar result

tests/php/phpstan.sh
| Description?  | Use the same version as it is defined un the composer.lock instead of using the latest 0.12 version
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/prestashop/ps_facetedsearch/420)
=> Use the same version as it is defined in the composer.lock

src/Filters/Converter.php
This pull request fix the issue with the ps_faceted search modules sub category filter. It is mixing what category it should fetch products from when there are several categories with the same name.
| Description?  | This pull request fix the issue with the sub category filter mixing what category it should fetch products from.
| Fixed ticket? | Fixes PrestaShop/Prestashop#24764.
| How to test?  | Follow instructions in Ticket.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/prestashop/ps_facetedsearch/449)
=> Fix for filter on subcategories with the same name

src/Filters/Block.php, src/Filters/Converter.php
| Description?  | The alphabetical order seems to be case-sensitive, as it takes into account possible capital letters when it should not. <br/>So I change function `strnatcmp` by case-insentitive alternative `strnatcasecmp`. <br/>I also remove useless call function `sortbykey` because categories and manufacturers are sort by `sortFiltersByLabel` function with `strnatcasecmp` in all cases.
| Fixed ticket? | Fixes PrestaShop/Prestashop#26444.
| How to test?  | See how to test section on issue.
--- …
=> Fixed order brands case sensitive

ps_facetedsearch.php, src/Form/Feature/FormDataProvider.php, src/Hook/AttributeGroup.php, src/Hook/Feature.php
| Description?  | By default put "indexable" option to No (instead of Yes) in add/edit attributes & features pages
| Fixed ticket? | Fixes PrestaShop/Prestashop#15170.
| How to test?  | Add an attribute group in **Catalog > Attributes & Features > Attributes** or a feature in **Catalog > Attributes & Features > Features**.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/prestashop/ps_facetedsearch/550)
=> By default put "indexable" option to No in add/edit attributes & features pages

src/Filters/Block.php, src/Filters/Converter.php, src/Filters/Products.php, src/Product/Search.php, tests/php/FacetedSearch/Filters/BlockTest.php, tests/php/FacetedSearch/Product/SearchTest.php
| Description?  | See below
| Type?         | bug fix / improvement
| Fixed ticket? | Fixes PrestaShop/Prestashop#14518
| How to test?  | See below
- This PR enables to filter products by quantity in stock, like it was in PrestaShop 1.6. You now have three options:
- Not available - shows product with zero quantity and disabled out-of-stock ordering. (not very useful but kept it - users can remove it in their TPL)
- Available - shows products in stock or with enabled out-of-stock ordering
- In stock - shows products in stock (new option I added)
1. Make 4 products
A. Quantity 0, disabled backorder.
B. Quantity 0, enabled backorder.
C. Quantity 1.
D. …
=> Enable filtering by stock properly

src/Hook/Configuration.php, src/HookDispatcher.php, tests/php/FacetedSearch/HookDispatcherTest.php
| Description?  | If caching option is enabled in faceted search, it caches the rendered blocks into database for faster loading. However, we must reload them if changing **Allow ordering of out-of-stock products** or **Enable stock management** in **Shop parameters > Product settings**. This PR does it automatically.
| Fixed ticket? | Fixes PrestaShop/Prestashop#25587
| How to test?  | See below.
**How to test**
- Install module, set it up, enable cache in it. Go any category in FO to load the cache up.
- Open your phpMyAdmin or Adminer and open table `ps_layered_filter_block`. There should be some data.
- Go to **Shop …
=> Flush cache if changing configuration related to stock

src/Filters/Block.php, src/Product/Search.php, tests/php/FacetedSearch/Filters/BlockTest.php, tests/php/FacetedSearch/Product/SearchTest.php
| Description?  | I made a logical mistake and left a legacy code which ignored products with negative quantities, when filtering for Available products. I also changed one line to improve clarity.
| Fixed ticket? | Fixes bug in my previous PR - https://github.com/PrestaShop/ps_facetedsearch/pull/479
| How to test?  | Make a product with Backorders allowed and quantity -1. It did not appear if you selected in "Available" in stock filter. Now it does.
Ping @rdy4ever and @hibatallahAouadni for quick QA 😄
--- …
=> Fix availability filter for products with negative quantities.

src/Adapter/MySQL.php
| Description?  | This PR fixes the issue when an array-type value is given to the `pSQL` function, since the `$values` variable could be a multi-dimensional array.
| Fixed ticket? | Fixes PrestaShop/Prestashop#27357.
| How to test?  | Please see PrestaShop/Prestashop#27357.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/prestashop/ps_facetedsearch/593)
=> Fix `strip_tags` error messages during value escaping.

src/Product/Search.php, tests/php/FacetedSearch/MockProxy.php, tests/php/FacetedSearch/Product/SearchTest.php
Products that were not accessible by the user were still visible on the listing
| Description?  | Verifies that the user has the right to access the product
| Type?         | bug fix 
| BC breaks?    |  no
| Fixed ticket? | Fixes PrestaShop/Prestashop#27601.
| How to test?  | **On Administration**<br/>1. On category  **Clothes**, go to sub-category **Men** and set access only to groups **Customer** <br/>2. Create a product **test** with only the category **Men**<br/>**On store**<br/>1. Go to the category **Clothes**<br/>2. Sub-category **Men** isn't display and you can't see the produt **test**
---
This change is [<img src="https://reviewable.io/review_button.svg" …
=> Check access to product on category listing

views/templates/front/catalog/facets.tpl
module **ps_facetedsearch**'s [facets.tpl](https://github.com/PrestaShop/ps_facetedsearch/blob/dde4153afad3b9ed5bebfcc6a326dc75b24ba43f/views/templates/front/catalog/facets.tpl#L19-L20) return `null` when there is no facet in FacetFilters widget
In turn, theme **classic-theme**'s [listing.js](https://github.com/PrestaShop/classic-theme/blob/0c1ecfaa3308d75bedb603c689a5300c7bc3dc56/_dev/js/listing.js#L177-L179) `replaceWith` replaces the whole `#search_filters` div (both inner content and the div itself) by
```
```
so the next **ajax render** can not finds `#search_filters` then can not renders its inner content as desired in next filters till the **whole page refresh**.
| Description?  | …
=> fix FacetFilters widget disappears after a no facet filter

_dev/back/index.js
Problem: [views/templates/admin/views.tpl](https://github.com/PrestaShop/ps_facetedsearch/blob/dev/views/templates/admin/view.tpl#L25)
cause web browser console error `function checkForm() is not defined` on form submit
| Description?  | Solution: attach function `checkForm()` in _dev/back/index.js to `window` object to make it becomes available in outside context
| Fixed ticket? | Fixes PrestaShop/Prestashop#23643
| How to test?  | Please follow the issue's Steps to reprocude before PR and after PR, do not forget to rebuild asset as well as clear web browser cache after PR.
---
This change is [<img …
=> Fix: BO - New filters template - an error is displayed in the console when we click save

config.xml, ps_facetedsearch.php, src/Hook/ProductSearch.php, upgrade/upgrade-3.9.0.php, views/templates/admin/manage.tpl
| Description?  | https://github.com/PrestaShop/PrestaShop/issues/27186
| Fixed ticket? | https://github.com/PrestaShop/PrestaShop/issues/27186
| How to test?  | :warning: there are more modules loading jquery.ui.  So before testing please disable the following modules: **ps_searchbar**, **ps_blockreassurance** and **ps_imageslider** :warning:  . Install this module your prestashop, (go to Modules management page and upgrade if you manually reuploaded it on top of older version - actually recommeded to do so to test the upgrade). Now you should be able to see additional option in module confuguration "Use Jquery UI …
=> Add configuration to use jquery ui slider

tests/php/phpstan/phpstan-latest.neon
| Description?  | Tests were reporting `Ignored error pattern ~^Access to an undefined property Cookie::\$id_lang\.$~ was not matched in reported errors.`, and "fail". This will fix it.
| Fixed ticket? | -
| How to test?  | See tests are green.
Example of failing tests on different PRs:
- https://github.com/PrestaShop/ps_facetedsearch/actions/runs/3338143641/jobs/5906764102
- https://github.com/PrestaShop/ps_facetedsearch/actions/runs/3331877803/jobs/5838854200
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/prestashop/ps …
=> Remove unreported error and fix tests

src/Filters/Block.php, src/Filters/DataAccessor.php
| Description?  | Read below
| How to test?  | Compare installs with and without this PR, they will provide the same results.
- There is no need to load a list of features or their values 30 times.
- There was already a mechanism to store loaded attributes, I implemented the same for features.
- I tried on my shop with a category that has 2592 products, 28 features and about 800 feature values.
- Average load time from 8 attempts 507 ms ➡️ 492 ms
- Database queries 386 ➡️ 359
- Peak memory usage 15,4 MB ➡️ 15,3 MB
- I think this can be tested by a dev. There is no difference to the returned data.
- - - …
=> Cache features in DataAccessor

src/Filters/Block.php, src/Filters/Converter.php, src/Filters/Products.php, src/Hook/ProductSearch.php, src/Product/Search.php, src/Product/SearchProvider.php, tests/php/FacetedSearch/Filters/BlockTest.php, tests/php/FacetedSearch/Filters/ConverterTest.php, tests/php/FacetedSearch/Product/SearchTest.php
| Description?  | See below
| Type?         | improvement / refacto
| BC breaks?    | yes
| How to test?  | This Pull Request refactors the code, but does not modify the behavior. You should be able to compare the module behavior with and without this PR : they should be identical
- When you open a category or other page, the controller first asks on a hook, if there is somebody who would like to search products for him. This module is hooked there and if it's category controller, it says "Hey I can do this filtering for you" and return it's instance.
- Then, category controller calls `runQuery()` function in this module and passes …
=> Remove use of `$_GET`, refacto, simplify

ps_facetedsearch.php, src/Hook/Category.php, views/templates/admin/manage.tpl
| Description?  | Read below. I tried to provide clear description of the feature with context and how it looks like. Please ask me if some things are not clear.
| Type?         | new feature
| Fixed ticket? | Fixes https://github.com/PrestaShop/PrestaShop/issues/28687
| How to test?  | Read below. I tried to provide clear 'how to test' items please ask me if some things are not clear.
- Half of merchants have no idea about any filter settings and you must non-stop keep checking, if you didn't forget to assign a template to new category after creating it. Merchants don't want to think about it.
- So, this PR adds a new function where you can select …
=> Add default filter functionality

ps_facetedsearch.php, src/Hook/Category.php
➡️ Note for QA and review - test are OK, the red is due to coveralls again.
| Description?  | My new function that automatically adds newly created categories to a default filter (added in https://github.com/PrestaShop/ps_facetedsearch/pull/728) does not work properly, because I forgot to call `$this->module->buildLayeredCategories();`. I use this oportunity to also clean up the related code a bit.
| Fixed ticket? | -
| How to test?  | Set up a default filter in faceted search. Go create a new category, add some product to it. Go to FO and see that you can see filters. Before, the category was added to the template, but the …
=> Fix adding new category

src/Filters/Block.php, src/Filters/Converter.php, src/Filters/Provider.php, src/Hook/ProductSearch.php, src/Product/SearchProvider.php, tests/php/FacetedSearch/Filters/BlockTest.php, tests/php/FacetedSearch/Filters/ConverterTest.php, tests/php/FacetedSearch/Product/SearchProviderTest.php
| Description?  | Some minor refactoring discovered when working on https://github.com/PrestaShop/ps_facetedsearch/pull/757, to reduce that PR's scope. Details below.
| Fixed ticket? | -
| How to test?  | Check that you see filters in front office and unit tests pass. No visible or behavior change.
- I unified two DB queries to a single `getFiltersForQuery` function. This function is now in a new class `Filters\Provider`. This class is now passed in some new constructors. `BlockTest` needed to be changed a tiny bit to add new lines.
- In `createFacetedSearchFiltersFromQuery`, I was using `$query->getIdCategory()` instead of …
=> Minor refactoring

src/Product/Search.php, tests/php/FacetedSearch/MockProxy.php, tests/php/FacetedSearch/Product/SearchTest.php
➡️ QA - read the PR description and test scenarios provided.
| Description?  | Read below.
| Deprecations? | 
| How to test?  | Try test scenarios below.
- This is another extracted part of https://github.com/PrestaShop/ps_facetedsearch/pull/757. 
- Basically, we have three "kinds" of filters that are applied to a search.
- Ones that are common for all pages (even for other controllers potentially) and are applied all the time, no matter what.
- Then you have filters that customers select in front office by themselves in left column.
- And you have the filters specific for the current controller, currently only a category …
=> Refacto applying filters, add tests

src/Product/SearchProvider.php
| Description?  | To format weight in "active filters" section, this module was still using `Tools::displayNumber`. This is deprecated since 1.7.5, minimum supported version of this module is 1.7.6.
| How to test?  | No QA needed.
No visible change except space between number and unit.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/PrestaShop/ps_facetedsearch/783)
=> Remove deprecated number format

src/Hook/ProductSearch.php
| Description?  | Do not respond and provide search provider instance, if there are no filters set up for this controller.
| Fixed ticket? | Fixes PrestaShop/Prestashop#31278
| How to test?  | Install develop, install faceted search, UNCHECK search page in your filter template. Go to FO, search for `THE ADVENTURE BEGINS FRAMED POSTER`, should find 2 products. Disable faceted search, see that the product order is still the same.
➡️ Position sort on this page is still not fixed, but it won't affect people if they don't want to use this module on the search page, which is marked as `experimental`.
- - -
This change …
=> Do not respond if there are no filters

src/Product/CoreSearchBackport.php, src/Product/Search.php, tests/php/phpstan/phpstan-1.7.6.neon, tests/php/phpstan/phpstan-1.7.7.neon, tests/php/phpstan/phpstan-1.7.8.neon
| Description?  | Instead of leveraging the search controller, which is not optimal for our usecase, I reimplemented a part of core search functionality to the module itself, which will make it as fast as the original provider.
| Type?         |  improvement
| How to test?  | See below.
**How to test**
- _You don't need to test other pages than search, they were not touched._
- _You don't need to test the filtering in the left column._
- Order of the products could be different compared to when the module is disabled, because the sorting by relevance is not yet implemented.
- **Do test** that the search page finds the same results …
=> Make search as fast as original provider

config.xml, ps_facetedsearch.php, src/Filters/Block.php, src/Filters/Converter.php, src/Product/Search.php, tests/php/FacetedSearch/Filters/BlockTest.php, tests/php/FacetedSearch/Filters/ConverterTest.php, tests/php/FacetedSearch/Product/SearchTest.php, upgrade/upgrade-3.12.0.php
| Description?  | I have unified the naming of availability filter. It was a mix and match of `quantity`/`availability` nomenclature, with both `TYPE_AVAILABILITY` and `TYPE_QUANTITY` constants existing. Added some comments here and there.
| BC breaks?    | No BC breaks, FO template was already using 'availability' naming.
| How to test?  | Check that filters show up and the availability filter works correctly.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/PrestaShop/ps_facetedsearch/780)
=> Unify availability filter naming

src/Adapter/MySQL.php
| Description?  | The module doesn't take into account the parameter 'visibility' configured for the shop context.
| Type?         | bug fix 
| BC breaks?    | yes / no
| Deprecations? | yes / no
| Fixed ticket? | Fixes PrestaShop/Prestashop#{issue number here}.
| How to test?  | Configure multishop. On the product page, configure the different "visibility" (both/none) per the shops. Current result: the module takes the 'visibility' from table 'product' that is wrong for some shop. Expected result: visibility of the product according to the configurations. 
- - - …
=> take into an account the "visibility" by shop

ps_facetedsearch.php
| Description?  | Fixes issue with checkboxes not working on 8.1 and errors in console. `_PS_JS_DIR_` is an url not a directory path, which is not very obvious without checking it's definition. `define('_PS_JS_DIR_', __PS_BASE_URI__.'js/');`
| Fixed ticket? | Fixes PrestaShop/Prestashop#32987
| How to test?  | Check that checkboxes stay checked after reopening the edit screen. I think this issue only happens when using prestashop in a subfolder - like `localhost/dev/`.
- - - …
=> Fix sortable path

src/Product/SearchProvider.php
| Description?  | See below
| How to test?  | 
- This PR passes the information of the found combination to the core. If it's not passed, the core will select the default combination.
- It allows the core to better show data in the listings, depending on the combination found - mainly the image, link, price. (see https://github.com/PrestaShop/PrestaShop/pull/33363)
- Even without that PR, you can see a difference, that if you filter for Black T-shirt, the link of the product it found will lead to black tshirt combination right away. With the mentioned PR, you will even see a black photo.
- So if you …
=> Pass attribute information with the results

upgrade/upgrade-3.13.0.php
| Description?  | We changed a logic of availability logic a bit (https://github.com/PrestaShop/ps_facetedsearch/pull/883#issuecomment-1648160837) and it would be good to flush block cache, users could see old values before their next CRON cleaning run.
| Type?         | 
| BC breaks?    |
| Deprecations? | 
| Fixed ticket? |
| How to test?  | Does not need QA - the same line of code is used when upgrading to previous version - https://github.com/PrestaShop/ps_facetedsearch/blob/dev/upgrade/upgrade-3.12.0.php.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/PrestaShop/ps_facetedsearch/884 …
=> Flush cache on upgrade

.github/workflows/js.yml, .github/workflows/php.yml
| Description?  | Recent PRs' tests have a lot of warnings about outdated Node, GH actions <br> (9 JS warnings and 21 PHP warnings in Release v3.13.1): <br> https://github.com/PrestaShop/ps_facetedsearch/actions/runs/5793944220 <br> https://github.com/PrestaShop/ps_facetedsearch/actions/runs/5793944222
| Deprecations? | yes
| Fixed ticket? | Fixes PrestaShop/Prestashop#{issue number here}.
| How to test?  | GH workflows complete with less warnings about outdated Node, PHP, actions.
- - - …
=> Update GH workflows: Node 14-16, PHP 7.2-8.2, Github actions v3

src/Hook/ProductSearch.php
| Description?  | Currently, there is an error in Prestashop, it loads the whole jQuery UI library instead of only the necessary components called by the modules<br>If we correct this on Prestashop, we must also correct this call which does not have the correct syntax, it simply lacks the "ui." before.<br>This will have no impact on previous versions of Prestashop but will optimize webperfs for future versions
| Fixed ticket? | Fixes PrestaShop/Prestashop#33563
| How to test?  | <p>Check on the Front side, the list of assets loaded in the network console of the web browser</p><p>Basic, you can test it will not change …
=> Fix load JqueryUI for load good component - Link PR Prestashop #33563

src/Adapter/InterfaceAdapter.php, src/Adapter/MySQL.php, src/Product/Search.php, src/Product/SearchProvider.php
| Description?  | When you open a page with no products, it shows empty availability filter. The same problem if you disable stock management. I did it wrong the last time. This PR fixes the issue. Also, I added some comments.
| How to test?  | Disable stock management in BO and see that there is no longer an empty filter in the left column.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/PrestaShop/ps_facetedsearch/916)
=> Fix empty stock filter, add comments

src/Product/SearchProvider.php
| Description?  | Add sorting by reference in the prestashop categorie page.
| How to test?  | Check that on the category with filters there is a new sorting option available
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/PrestaShop/ps_facetedsearch/925)
=> Add sorting by reference

tests/php/phpstan.sh
| Description?  | The previous way of removing the directory didn't work correctly.
| Fixed ticket? | This is just a copy of https://github.com/PrestaShop/blockreassurance/pull/594
| How to test?  | CI is 🟢 (with less random php-test `rm -rf` failures)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/PrestaShop/ps_facetedsearch/929)
=> Fix removing previous module files in PHPStan tests

.htaccess, controllers/front/cron.php, ps_facetedsearch-attribute-indexer.php, ps_facetedsearch-clear-cache.php, ps_facetedsearch-price-indexer.php, ps_facetedsearch.php
| Description?  | Allow executing only the specific PHP files as external endpoints, required since PrestaShop 9.0 because additional security was added in this PR https://github.com/PrestaShop/PrestaShop/pull/34184 The idea in this PR is to allow access to very specific files to prevent unwanted accesses on malicious files
| How to test?  | Install a shop based on develop branch, go to the module administration of faceted search and try to build indexes or clear the cache. An error message should appear and when you check the network in browser developer tools you should see that the ajax request was …
=> Deprecate standalone endpoints to match PrestaShop 9.0 new security policy

src/Form/Attribute/FormModifier.php, src/Form/AttributeGroup/FormModifier.php, src/Form/Feature/FormModifier.php, src/Form/FeatureValue/FormModifier.php
| Description?  | Use loose typing in classes as the core uses different Translator override and decoration that mess with the initial type, also with this the module should remain compatible with more PrestaShop versions
| How to test?  | This PR only needs to be tested with the develop branch from the core, to validate it fixes the bug that prevents finishing the Attributes page However, the next release PR of the module should be tested with older versions like 8.1 or 8.0 or even as low as 1.7.6 since it's the minimum range
=> Use loose type for Translator

src/Product/CoreSearchBackport.php
| Description?  | In preparation to finalize search controller support, our backport needs to return items in proper position, which we can later use. 
| How to test?  | This is an experimental feature and does not need testing.
=> Make backport return items ordered by position

src/Hook/ProductSearch.php, src/Product/SearchProvider.php, tests/php/FacetedSearch/Product/SearchProviderTest.php
| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | Fix PHP 8.4 compatibility
| Type?             | refactor
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | 
| Sponsor company   | 
| How to test?      |
=> Fix PHP 8.4 compatibility

ps_facetedsearch.php
The fixed filters are 7 and not 6, and they are as follows:
1. Sub-categories filter
2. Product stock filter
3. Product extras filter
4. Product condition filter
5. Product brand filter
6. Product weight filter (slider)
7. Product price filter (slider)
| Description?  | see https://github.com/PrestaShop/PrestaShop/issues/37587
| Fixed ticket? | https://github.com/PrestaShop/PrestaShop/issues/37587
| How to test?  | see https://github.com/PrestaShop/PrestaShop/issues/37587
=> Fix: ps_facetedsearch - In template creation, filters counter in BO is not correct

ps_facetedsearch.php, src/Adapter/MySQL.php, src/Product/SearchProvider.php
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Description?      | Fixes search result ordering in case of ordering by relevance. ✅ It provides the same results as the default page. ✅ I made sure that it returns `Relevance` sort order with proper asc/desc for search and other pages. ✅ It properly sorts with relevance orders if passed to the URL. ✅ Both default relevance and manually selected in URL by `&order=product.position.desc` return the same results.
| Type?             | bug fix
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | 
| How to test?      | Result order should be the same with and without faceted search installed.
| Sponsor company   | 
Without faceted search
With faceted search
=> Provide proper product order on search page
