ps_facetedsearch.php

Fix SQL error on 'order by' column

---

views/templates/admin/add.tpl

Some strings were uploaded to Crowdin in a wrong format: `sprintf('Feature: %1$s (%2$d value)',$_smarty_tpl->tpl_vars['feature']->value['name'],$_smarty_tpl->tpl_vars['feature']->value['n'])`

Fix sprintf strings

---

ps_facetedsearch.php

See http://forge.prestashop.com/browse/BOOM-1476

Prevented SQL injections

---

ps_facetedsearch.php

http://forge.prestashop.com/browse/BOOM-1476

Prevented backquote escape

---

ps_facetedsearch.php
src/Ps_FacetedsearchFacetsURLSerializer.php
src/Ps_FacetedsearchFiltersConverter.php
src/Ps_FacetedsearchProductSearchProvider.php
src/Ps_FacetedsearchRangeAggregator.php
tests/BlockLayeredFacetsURLSerializerTest.php
tests/BlockLayeredRangeAggregatorTest.php

Widgetize module

---

ps_facetedsearch.php

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/prestashop/ps_facetedsearch/25)

Make the search more cacheable & scalable by removing temp table creation

---

ps_facetedsearch.php

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/prestashop/ps_facetedsearch/32)

Fix computation of caches with a lot of features in the database

---

ps_facetedsearch.php

Fixed order in implode function arguments
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/prestashop/ps_facetedsearch/36)

Fixed order in implode

---

config.xml
ps_facetedsearch.php

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/prestashop/ps_facetedsearch/42)

Bump version to 2.2.0

---

composer.json
config.xml
ps_facetedsearch.php

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/prestashop/ps_facetedsearch/41)

Deploying v2.2.0

---

ps_facetedsearch.php

https://github.com/PrestaShop/PrestaShop/issues/10018
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/prestashop/ps_facetedsearch/43)

Fix [BOOM-2025] ps_facetedsearch - Filter products by the stock of matched variants, not just any of them

---

config.xml
ps_facetedsearch.php

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/prestashop/ps_facetedsearch/45)

Bump version to 2.2.1

---

composer.json
config.xml
ps_facetedsearch.php

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/prestashop/ps_facetedsearch/46)

Deploying v2.2.1 of Faceted Search

---

src/Adapter/AbstractAdapter.php
src/Adapter/InterfaceAdapter.php
src/Adapter/MySQL.php
tests/php/FacetedSearch/Adapter/MySQLTest.php

Fixes first part of: https://github.com/PrestaShop/PrestaShop/issues/13839
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/prestashop/ps_facetedsearch/59)

Repair custom order

---

.travis.yml

Run PhpStan on all 1.7 versions of PrestaShop
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/prestashop/ps_facetedsearch/61)

Run PhpStan on all 1.7 versions of PrestaShop

---

src/Product/Search.php
tests/php/FacetedSearch/Product/SearchTest.php

Fix: https://github.com/PrestaShop/PrestaShop/issues/13902
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/prestashop/ps_facetedsearch/63)

Fix missing visibility check

---

config.xml
ps_facetedsearch.php

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/prestashop/ps_facetedsearch/64)

Bump to version 3.0.1

---

ps_facetedsearch.php

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/prestashop/ps_facetedsearch/66)

Restore widgets methods

---

config.xml
ps_facetedsearch.php

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/prestashop/ps_facetedsearch/67)

Bump to version 3.0.2

---

ps_facetedsearch.php
upgrade/upgrade-3.0.0.php

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/prestashop/ps_facetedsearch/69)

Only rebuild table while upgrading to prevent a fatal error with memory

---

src/Filters/Block.php
tests/php/FacetedSearch/Filters/BlockTest.php
tests/php/FacetedSearch/MockProxy.php
tests/php/FacetedSearch/Product/SearchTest.php

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/prestashop/ps_facetedsearch/71)

Add more tests for block search

---

src/Adapter/MySQL.php
src/Product/Search.php
tests/php/FacetedSearch/Adapter/MySQLTest.php
tests/php/FacetedSearch/Product/SearchTest.php

Fix https://github.com/PrestaShop/PrestaShop/issues/13985
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/prestashop/ps_facetedsearch/72)

filtering doesn't filter between product attributes

---

src/Filters/Block.php
tests/php/FacetedSearch/Filters/BlockTest.php
tests/php/FacetedSearch/MockProxy.php
tests/php/FacetedSearch/Product/SearchTest.php

Reverts PrestaShop/ps_facetedsearch#71
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/prestashop/ps_facetedsearch/78)

Revert "Add more tests for block search"

---

ps_facetedsearch-attribute-indexer.php
ps_facetedsearch-price-indexer.php
ps_facetedsearch.php
src/Filters/Block.php

Reverts PrestaShop/ps_facetedsearch#70
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/prestashop/ps_facetedsearch/77)

Revert "Reindex multistore correctly"

---

ps_facetedsearch-attribute-indexer.php
ps_facetedsearch-price-indexer.php
ps_facetedsearch.php
src/Filters/Block.php

#70 targeting the correct branch
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/prestashop/ps_facetedsearch/79)

Multistore

---

src/Filters/Block.php
tests/php/FacetedSearch/Filters/BlockTest.php
tests/php/FacetedSearch/MockProxy.php
tests/php/FacetedSearch/Product/SearchTest.php

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/prestashop/ps_facetedsearch/80)

More tests

---

src/Product/Search.php
tests/php/FacetedSearch/Product/SearchTest.php

Fixes https://github.com/PrestaShop/PrestaShop/issues/14120
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/prestashop/ps_facetedsearch/87)

Make features great again

---

src/Filters/Block.php
src/Hook/ProductSearch.php
src/Product/SearchProvider.php
tests/php/FacetedSearch/HookDispatcherTest.php
tests/php/FacetedSearch/Interface/FacetsRendererInterface.php
tests/php/FacetedSearch/Interface/ProductSearchProviderInterface.php
tests/php/FacetedSearch/Interface/WidgetInterface.php
tests/php/FacetedSearch/MockProxy.php
tests/php/FacetedSearch/Product/SearchProviderTest.php
tests/php/FacetedSearch/URLSerializerTest.php
tests/php/bootstrap.php
tests/php/phpunit.xml

Fixes https://github.com/PrestaShop/PrestaShop/issues/14082
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/prestashop/ps_facetedsearch/86)

Do not erase filter when multiple selection is not accepted

---

src/Adapter/MySQL.php
tests/php/FacetedSearch/Adapter/MySQLTest.php

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/prestashop/ps_facetedsearch/88)

Select on multishop table instead product table

---

ps_facetedsearch.php

Fixes https://github.com/PrestaShop/PrestaShop/issues/14140
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/prestashop/ps_facetedsearch/90)

Price indexing stopped working on PS1.7.5

---

config.xml
ps_facetedsearch.php

Bump to 3.0.4
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/prestashop/ps_facetedsearch/91)

Bump to 3.0.4

---

src/Adapter/AbstractAdapter.php
src/Adapter/InterfaceAdapter.php
src/Adapter/MySQL.php
src/Filters/Block.php
tests/php/FacetedSearch/Filters/BlockTest.php

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/prestashop/ps_facetedsearch/93)

Make sure initial population is reset

---

src/Filters/Block.php
src/Product/SearchProvider.php
tests/php/FacetedSearch/Filters/BlockTest.php

Fixes https://github.com/PrestaShop/PrestaShop/issues/14230
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/prestashop/ps_facetedsearch/97)

Fix the display of wrong Availability count 

---

config.xml
ps_facetedsearch.php

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/prestashop/ps_facetedsearch/98)

Bump to 3.0.5

---

config.xml
ps_facetedsearch.php

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/prestashop/ps_facetedsearch/106)

Bump to 3.0.6

---

src/Hook/Attribute.php
src/Hook/AttributeGroup.php
src/Hook/Feature.php
src/Hook/FeatureValue.php

Fixes https://github.com/PrestaShop/PrestaShop/issues/14488
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/prestashop/ps_facetedsearch/110)

Do not use seoUrl if user do not want to use it

---

ps_facetedsearch.php

* New DB table: layered_filter_block
* Removed DB Table: layered_friendly_url
* layered_filter
* filters => LONGTEXT
* layered_price_index
* + id_country
* index to replace
* layered_category
* charset latin1 -> utf8
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/prestashop/ps_facetedsearch/94)

Uninstall module used on PS 1.6 before using this one

---

config.xml
ps_facetedsearch.php

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/prestashop/ps_facetedsearch/112)

Bump to 3.1.0

---

src/Filters/Block.php
src/Filters/Converter.php
src/Hook/Attribute.php
src/Hook/AttributeGroup.php
src/Hook/Feature.php
src/Hook/FeatureValue.php

Fixes https://github.com/PrestaShop/PrestaShop/issues/14677
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/prestashop/ps_facetedsearch/114)

Use texture and color attribute only when color_type is set

---

src/Filters/Block.php
src/Filters/Converter.php
src/Product/SearchProvider.php
tests/php/FacetedSearch/Filters/ConverterTest.php
tests/php/FacetedSearch/Mock/Facet.php
tests/php/FacetedSearch/Mock/Filter.php
tests/php/bootstrap.php
tests/php/phpunit.xml

Fixes https://github.com/PrestaShop/PrestaShop/issues/14769
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/prestashop/ps_facetedsearch/116)

In faceted search, Manufacturers are displayed using ordering by id, instead of name

---

src/Adapter/AbstractAdapter.php
src/Adapter/InterfaceAdapter.php
src/Adapter/MySQL.php
src/Filters/Block.php
src/Product/Search.php
src/Product/SearchProvider.php
tests/php/FacetedSearch/Filters/BlockTest.php

Fixes https://github.com/PrestaShop/PrestaShop/issues/14734
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/prestashop/ps_facetedsearch/119)

Number of product are not ok after selecting filters

---

config.xml
ps_facetedsearch.php

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/prestashop/ps_facetedsearch/120)

Bump to 3.2.0

---

src/Adapter/AbstractAdapter.php
src/Adapter/InterfaceAdapter.php
src/Adapter/MySQL.php
src/Filters/Block.php
src/Product/Search.php
tests/php/FacetedSearch/Adapter/MySQLTest.php
tests/php/FacetedSearch/Filters/BlockTest.php
tests/php/FacetedSearch/Product/SearchTest.php

Ping @marionf 
Should fix: https://github.com/PrestaShop/PrestaShop/issues/15103
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/prestashop/ps_facetedsearch/123)

Better way to check for operations filters

---

config.xml
ps_facetedsearch.php

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/prestashop/ps_facetedsearch/127)

Bump to version 3.2.1

---

src/Adapter/AbstractAdapter.php
src/Adapter/InterfaceAdapter.php
src/Adapter/MySQL.php
src/Filters/Block.php
src/Product/Search.php
src/Product/SearchProvider.php
tests/php/FacetedSearch/Adapter/MySQLTest.php
tests/php/FacetedSearch/Filters/BlockTest.php

Reverts PrestaShop/ps_facetedsearch#132

Revert "Calculate the number of available products with the stock management"

---

config.xml
ps_facetedsearch.php

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/prestashop/ps_facetedsearch/140)

Update version to 3.3.0

---

src/Product/SearchProvider.php
tests/php/FacetedSearch/Product/SearchProviderTest.php
upgrade/upgrade-3.3.0.php

Fixes https://github.com/PrestaShop/PrestaShop/issues/15608
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/prestashop/ps_facetedsearch/143)

Reset page filter when using slider

---

config.xml
ps_facetedsearch.php

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/prestashop/ps_facetedsearch/147)

Update version to 3.4.0

---

upgrade/upgrade-3.4.1.php

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/prestashop/ps_facetedsearch/152)

Apply php-cs-fixer

---

.gitignore
config.xml
ps_facetedsearch.php
upgrade/upgrade-3.4.1.php

| Branch?       | develop
| Description?  | Merge master into dev
| How to test?  | No QA needed
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/prestashop/ps_facetedsearch/153)

Merge master into dev

---

config.xml
ps_facetedsearch.php

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/prestashop/ps_facetedsearch/164)

Bump to 3.5.0

---

views/templates/front/catalog/active-filters.tpl

https://github.com/PrestaShop/PrestaShop/issues/17993
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/prestashop/ps_facetedsearch/166)

remove trailing space

---

composer.lock
ps_facetedsearch.php
src/Adapter/MySQL.php
src/Filters/Block.php
src/Filters/Converter.php
src/Filters/Products.php
src/Hook/AbstractHook.php
src/Hook/Feature.php
src/Hook/ProductSearch.php
src/Product/Search.php
src/Product/SearchProvider.php
src/URLSerializer.php
tests/php/FacetedSearch/Adapter/MySQLTest.php
tests/php/FacetedSearch/Filters/BlockTest.php
tests/php/FacetedSearch/Filters/ConverterTest.php
tests/php/FacetedSearch/HookDispatcherTest.php
tests/php/FacetedSearch/Product/SearchProviderTest.php
tests/php/FacetedSearch/Product/SearchTest.php
tests/php/phpstan/bootstrap.php
upgrade/upgrade-3.4.1.php
upgrade/upgrade-3.6.0.php
views/templates/admin/manage.tpl

Fixes https://github.com/PrestaShop/PrestaShop/issues/18618
How to test:
Must be enabled by default after an update or a fresh install:
If you disable the cache systme, the table `ps_layered_filter_block` mustn't be populate by new data:
Sql request: 
```sql
select * from ps_layered_filter_block
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/prestashop/ps_facetedsearch/169)

Add option to enable / disable cache system

---

.prettyci.composer.json

Following example here https://github.com/PrestaShop/PrestaShop/pull/18029
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/prestashop/ps_facetedsearch/174)

Remove prettyCI config file

---

ps_facetedsearch-price-indexer.php
ps_facetedsearch.php

| Description?  | Remove unwanted part of code
| Fixed ticket? | Fixes https://github.com/PrestaShop/PrestaShop/issues/19849
| How to test?  | See issue.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/prestashop/ps_facetedsearch/177)

Remove useless part of code

---

config.xml
ps_facetedsearch.php

| Description?  | Bump version to 3.6.0
| How to test?  | No need QA
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/prestashop/ps_facetedsearch/191)

Bump to 3.6.0

---

webpack.config.js

| Description?  | Use the new version of CleanWebpackPlugin, this dependency has been updated by dependabot.
| How to test?  | No need QA.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/prestashop/ps_facetedsearch/203)

Use the new version of CleanWebpackPlugin

---

_dev/back/index.js
_dev/cldr/number-formatter.js
_dev/cldr/specifications/price.js
_dev/front/urlparser.js
package-lock.json
package.json

| Description?  | Dependabot PR to update airbnb eslint config was broken because of eslint errors
| How to test?  | No QA needed
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/prestashop/ps_facetedsearch/244)

Bump eslint-config-airbnb-base from 13.2.0 to 14.2.0

---

.github/workflows/php.yml

| Description?  | The configuration is broken.
| How to test?  | No need QA.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/prestashop/ps_facetedsearch/273)

Fix PHPStan configuration

---

composer.json

| Description?  | Fixed invalid composer.json
| Fixed ticket? | N/A
| How to test?  | **BEFORE the PR :** <br>![image](https://user-images.githubusercontent.com/1533248/101171552-3599a280-3640-11eb-95bd-575916069d1b.png)<br>**AFTER the PR :**<br>![image](https://user-images.githubusercontent.com/1533248/101171460-16027a00-3640-11eb-999f-0b112f2103b2.png)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/prestashop/ps_facetedsearch/274)

Fixed invalid composer.json

---

.github/workflows/php.yml
tests/php/phpstan.sh
tests/php/phpstan/phpstan-1.7.1.2.neon
tests/php/phpstan/phpstan-1.7.2.5.neon
tests/php/phpstan/phpstan-1.7.3.4.neon
tests/php/phpstan/phpstan-1.7.4.4.neon
tests/php/phpstan/phpstan-1.7.5.1.neon
tests/php/phpstan/phpstan-1.7.6.9.neon
tests/php/phpstan/phpstan-latest.neon
tests/php/phpstan/phpstan.neon

| Description?  | Make sure errors are correctly fixed in versions and add the 1.7.6.9 into the CI
| How to test?  | GA is green.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/prestashop/ps_facetedsearch/276)

Update phpstan to handle PS versions properly

---

.github/workflows/php.yml

| Description?  | We want to control which version of dependencies we used..
| How to test?  | Qa is green.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/prestashop/ps_facetedsearch/278)

Fix cs fixer

---

src/Filters/Converter.php
src/Hook/ProductSearch.php
src/Product/SearchProvider.php
src/URLSerializer.php
tests/php/FacetedSearch/Filters/ConverterTest.php
tests/php/FacetedSearch/URLSerializerTest.php
tests/php/phpstan/phpstan-1.7.6.9.neon
tests/php/phpstan/phpstan-latest.neon

| Description?  | Correctly serialize and unserialize parameters in URLs.
| BC breaks?    | yes
| Deprecations? | yes
| Fixed ticket? | Fixes PrestaShop/Prestashop#16320
| How to test?  | See ticket.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/prestashop/ps_facetedsearch/275)

Correctly serialize and unserialize parameters in URLs.

---

config.xml
ps_facetedsearch.php

| Description?  | Bump to 3.7.0.
| Type?         |  improvement
| How to test?  | Nope.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/prestashop/ps_facetedsearch/279)

Bump version to 3.7.0

---

.github/workflows/php.yml

| Description?  | Use PHP7.4 instead of PHP8.
| BC breaks?    | o
| How to test?  | No need QA.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/prestashop/ps_facetedsearch/294)

Fix cs fixer action

---

ps_facetedsearch.php

| Description?  | Make sure prices are cast into int.
| Fixed ticket? | Fixes PrestaShop/Prestashop#22622
| How to test?  | see issue.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/prestashop/ps_facetedsearch/299)

Cast value when saving prices

---

.github/workflows/build-release.yml

| Description?  | We don't need to build a release on each pull request
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/prestashop/ps_facetedsearch/378)

Use build release action only when a push is done on the master branch

---

.github/workflows/php.yml
.gitignore
tests/php/phpunit.xml

| Description?  | Added Coveralls
| Fixed ticket? | N/A
| How to test?  | Data is pushed to Coveralls : https://coveralls.io/github/PrestaShop/ps_facetedsearch
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/prestashop/ps_facetedsearch/386)

Added Coveralls

---

.gitignore
README.md

| Description?  | The compiled assets folder has changed, updated README.md for the minimum compatibility with node, and .gitignore file to ignore the /views/dist folder
| How to test?  | Try to compile assets with node v10 or v12, it will fail, the minimum compatibility seems v14
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/prestashop/ps_facetedsearch/758)

Update .gitignore and README.md with new specs

---

ps_facetedsearch.php

| Description?  | Please be specific when describing the PR. <br> Every detail helps: versions, browser/server configuration, specific module/theme, etc. Feel free to add more information below this table.
| Type?         | bug fix / improvement / new feature / refacto / critical
| BC breaks?    | yes / no
| Deprecations? | yes / no
| Fixed ticket? | Fixes PrestaShop/Prestashop#{issue number here}.
| How to test?  | Please indicate how to best verify that this PR is correct.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/prestashop/ps_facetedsearch/768)

Bump version number to 3.10

---

ps_facetedsearch.php
src/Hook/Attribute.php
src/Hook/AttributeGroup.php
src/Hook/Feature.php
src/Hook/FeatureValue.php

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | This method will be removed.
| Type?             | improvement
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | CI 🟢 & automated tests
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/PrestaShop/ps_facetedsearch/777)

Fix deprecated usage

---

upgrade/upgrade-3.11.0.php

| Description?  | Adds safety check to upgrade. Does not need QA, will be tested on release.
| How to test?  |
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/PrestaShop/ps_facetedsearch/786)

Add condition to upgrade

---

config.xml
ps_facetedsearch.php

| Description?  | Please be specific when describing the PR. <br> Every detail helps: versions, browser/server configuration, specific module/theme, etc. Feel free to add more information below this table.
| Type?         | bug fix / improvement / new feature / refacto / critical
| BC breaks?    | yes / no
| Deprecations? | yes / no
| Fixed ticket? | Fixes PrestaShop/Prestashop#{issue number here}.
| How to test?  | Please indicate how to best verify that this PR is correct.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/PrestaShop/ps_facetedsearch/790)

Bump version number to 3.11.1

---

config.xml
ps_facetedsearch.php

| Description?  | Bump version to 3.13.1
| Type?         | 
| BC breaks?    | 
| Deprecations? | 
| How to test?  | 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/PrestaShop/ps_facetedsearch/888)

Bump version to 3.13.1

---

views/templates/front/catalog/facets.tpl

| Description?  | Added `data-type` to distinguish facet for improving tests on modules
| Fixed ticket? | N/A
| How to test?  | N/A
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/PrestaShop/ps_facetedsearch/893)

Added `data-type` to distinguish facet

---

config.xml
ps_facetedsearch.php

| Description?  | Bump version to 3.13.2
| Type?         | 
| BC breaks?    | 
| Deprecations? | 
| How to test?  |
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/PrestaShop/ps_facetedsearch/922)

Bump version to 3.13.2

---

config.xml
ps_facetedsearch.php

| Description?  | Bump version 3.14.1
| Type?         |
| BC breaks?    | 
| Deprecations? |
| How to test?  |

Bump version 3.14.1

---

config.xml
ps_facetedsearch.php

| Description?  | Bump version 3.15.1
| How to test?  | ~

Bump version 3.15.1

---

.github/workflows/php.yml
composer.json
composer.lock
config.xml
ps_facetedsearch.php

| Description?  | Bump Version 4.0.0, also update minimum PHP version to 7.1 which implies minimum PrestaShop version to 1.7.7, which imply a new major version
| Type?         | new feature
| BC breaks?    | yes
| How to test?  | ~

Bump Version 4.0.0
